/************** TABLAS PARA EJERCICIOS ONE-TO-ONE ***************/
CREATE SEQUENCE estudiantes_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE estudiantes(
   id INT GENERATED BY DEFAULT AS SEQUENCE estudiantes_id_seq,      
   nombre VARCHAR(600),
   apellido VARCHAR(500),   
   PRIMARY KEY(id)   
);

CREATE SEQUENCE info_estudiantes_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE info_estudiantes(
   id INT GENERATED BY DEFAULT AS SEQUENCE info_estudiantes_id_seq,
   id_estudiante INT,
   ciudad VARCHAR(600),
   telefono VARCHAR(500),
   PRIMARY KEY(id),   
   FOREIGN KEY(id_estudiante) REFERENCES estudiantes,
);


CREATE SEQUENCE personas_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE personas(
   id INT GENERATED BY DEFAULT AS SEQUENCE personas_id_seq,      
   nombre VARCHAR(600),
   email VARCHAR(500),   
   PRIMARY KEY(id)   
);


CREATE SEQUENCE pasaporte_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE pasaportes(
   id INT GENERATED BY DEFAULT AS SEQUENCE pasaporte_id_seq,      
   id_persona INT,
   numero_pasaporte VARCHAR(600),
   PRIMARY KEY(id),
   FOREIGN KEY(id_persona) REFERENCES personas   
);

/************** TABLAS PARA EJERCICIOS ONE-TO-ONE ***************/

CREATE SEQUENCE pedidos_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE pedidos(
   id INT GENERATED BY DEFAULT AS SEQUENCE pedidos_id_seq,      
   id_persona INT,
   producto VARCHAR(600),
   precio FLOAT,
   PRIMARY KEY(id),
   FOREIGN KEY(id_persona) REFERENCES personas   
);


/************** DATOS DE PRUEBA ***************/

INSERT INTO estudiantes VALUES(DEFAULT,'Bart','Simpson');
INSERT INTO estudiantes VALUES(DEFAULT,'Matt','Groening');
INSERT INTO estudiantes VALUES(DEFAULT,'Harry','Potter');
INSERT INTO info_estudiantes VALUES(DEFAULT,1,'Springfield','(939)-555-0113');
INSERT INTO info_estudiantes VALUES(DEFAULT,2,'Shelbyville','(111)-671-9871');


INSERT INTO personas VALUES(DEFAULT,'Juan','juan@mail.com');
INSERT INTO personas VALUES(DEFAULT,'Alfredo','alfredo@mail.com');
INSERT INTO personas VALUES(DEFAULT,'Francisco','francisco@mail.com');
INSERT INTO pasaportes VALUES(DEFAULT, 1,'A4DEK33D');
INSERT INTO pasaportes VALUES(DEFAULT, 2,'V5ALH99I');

INSERT INTO pedidos VALUES(DEFAULT,1,'Papas Sabritas',25.50);
INSERT INTO pedidos VALUES(DEFAULT,1,'Refresco 2Lt',30.50);