/************** TABLAS PARA EJERCICIOS ONE-TO-ONE ***************/
CREATE SEQUENCE estudiantes_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE estudiantes(
   id INT GENERATED BY DEFAULT AS SEQUENCE estudiantes_id_seq,      
   nombre VARCHAR(600),
   apellido VARCHAR(500),   
   PRIMARY KEY(id)   
);

CREATE SEQUENCE info_estudiantes_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE info_estudiantes(
   id INT GENERATED BY DEFAULT AS SEQUENCE info_estudiantes_id_seq,
   id_estudiante INT,
   ciudad VARCHAR(600),
   telefono VARCHAR(500),
   PRIMARY KEY(id),   
   FOREIGN KEY(id_estudiante) REFERENCES estudiantes,
);


CREATE SEQUENCE personas_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE personas(
   id INT GENERATED BY DEFAULT AS SEQUENCE personas_id_seq,      
   nombre VARCHAR(600),
   email VARCHAR(500),   
   PRIMARY KEY(id)   
);


CREATE SEQUENCE pasaporte_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE pasaportes(
   id INT GENERATED BY DEFAULT AS SEQUENCE pasaporte_id_seq,      
   id_persona INT,
   numero_pasaporte VARCHAR(600),
   PRIMARY KEY(id),
   FOREIGN KEY(id_persona) REFERENCES personas   
);

/************** TABLAS PARA EJERCICIOS ONE-TO-MANY ***************/

CREATE SEQUENCE pedidos_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE pedidos(
   id INT GENERATED BY DEFAULT AS SEQUENCE pedidos_id_seq,      
   id_persona INT,
   producto VARCHAR(600),
   precio FLOAT,
   PRIMARY KEY(id),
   FOREIGN KEY(id_persona) REFERENCES personas   
);

/************** TABLAS PARA EJERCICIOS MANY-TO-MANY ***************/
CREATE SEQUENCE libros_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE libros(
   id INT GENERATED BY DEFAULT AS SEQUENCE libros_id_seq,      
   titulo VARCHAR(1000),
   precio FLOAT,
   PRIMARY KEY(id)
);


CREATE SEQUENCE autores_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE autores(
   id INT GENERATED BY DEFAULT AS SEQUENCE autores_id_seq,      
   nombre VARCHAR(1000),
   PRIMARY KEY(id)
);

CREATE TABLE autores_libros(
   id_autor INT,
   id_libro INT, 
   PRIMARY KEY(id_autor, id_libro),
   FOREIGN KEY(id_autor) REFERENCES autores,
   FOREIGN KEY(id_libro) REFERENCES libros
);



CREATE SEQUENCE cursos_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE cursos(
   id INT GENERATED BY DEFAULT AS SEQUENCE cursos_id_seq,      
   nombre_curso VARCHAR(1000),
   PRIMARY KEY(id)
);

CREATE TABLE estudiantes_cursos(
  id_estudiante INT,
  id_curso INT,
  PRIMARY KEY(id_estudiante, id_curso),
  FOREIGN KEY(id_estudiante) REFERENCES estudiantes,
  FOREIGN KEY(id_curso) REFERENCES cursos
);

/************** DATOS DE PRUEBA ***************/


/* datos para ejemplo 1-1*/
INSERT INTO estudiantes VALUES(DEFAULT,'Bart','Simpson');
INSERT INTO estudiantes VALUES(DEFAULT,'Matt','Groening');
INSERT INTO estudiantes VALUES(DEFAULT,'Harry','Potter');
INSERT INTO info_estudiantes VALUES(DEFAULT,1,'Springfield','(939)-555-0113');
INSERT INTO info_estudiantes VALUES(DEFAULT,2,'Shelbyville','(111)-671-9871');

/* datos para ejercicio 1-1*/
INSERT INTO personas VALUES(DEFAULT,'Juan','juan@mail.com');
INSERT INTO personas VALUES(DEFAULT,'Alfredo','alfredo@mail.com');
INSERT INTO personas VALUES(DEFAULT,'Francisco','francisco@mail.com');
INSERT INTO pasaportes VALUES(DEFAULT, 1,'A4DEK33D');
INSERT INTO pasaportes VALUES(DEFAULT, 2,'V5ALH99I');


/* datos para ejercicio 1-N*/
INSERT INTO pedidos VALUES(DEFAULT,1,'Papas Sabritas',25.50);
INSERT INTO pedidos VALUES(DEFAULT,1,'Refresco 2Lt',30.50);

/* datos para ejemplo N-N*/
INSERT INTO autores VALUES(DEFAULT,'Kathy Sierra');
INSERT INTO autores VALUES(DEFAULT,'Bert Bates');
INSERT INTO autores VALUES(DEFAULT,'Bryan Basham');
INSERT INTO autores VALUES(DEFAULT,'Gregory Chaitin');
INSERT INTO autores VALUES(DEFAULT,'Lynn Margulis');

INSERT INTO libros VALUES(DEFAULT, 'Head First Java',800);
INSERT INTO libros VALUES(DEFAULT, 'Head First Servlets & JSP',850);
INSERT INTO libros VALUES(DEFAULT, 'Demostrando a Darwin',250);
INSERT INTO libros VALUES(DEFAULT, 'Planeta simbiótico',240);

INSERT INTO autores_libros VALUES(1,1);
INSERT INTO autores_libros VALUES(2,1);
INSERT INTO autores_libros VALUES(1,2);
INSERT INTO autores_libros VALUES(3,2);
INSERT INTO autores_libros VALUES(4,3);
INSERT INTO autores_libros VALUES(5,4);

/* datos para ejercicio N-N*/
INSERT INTO cursos VALUES(1,'Historia');
INSERT INTO cursos VALUES(2,'Pociones');
INSERT INTO cursos VALUES(3,'Computación');

INSERT INTO estudiantes_cursos VALUES(1,1);
INSERT INTO estudiantes_cursos VALUES(2,1);
INSERT INTO estudiantes_cursos VALUES(3,2);
INSERT INTO estudiantes_cursos VALUES(1,3);
INSERT INTO estudiantes_cursos VALUES(2,3);
INSERT INTO estudiantes_cursos VALUES(3,3);

